name: Publish to Dev.to

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
    paths:
      - 'articles/**.md'  # Only trigger for Markdown files in the 'articles' folder

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dev.to CLI
        run: npm install -g @sinedied/devto-cli

      - name: Publish to Dev.to
        run: npx @sinedied/devto-cli push articles/*.md --token ${{ secrets.DEVTO_API_KEY }} --repo ${{ github.repository }}