name: Publish to Dev.to

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
    paths:
      - 'articles/**.md'  # Only trigger for Markdown files in the 'articles' folder

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Find and publish articles
        run: |
          for file in articles/*.md; do
            if [ -f "$file" ]; then
              echo "Publishing $file to Dev.to..."
              CONTENT=$(cat "$file")
              JSON_PAYLOAD=$(jq -n \
                --arg content "$CONTENT" \
                '{"article": {"body_markdown": $content}}')
              
              # Send to Dev.to API
              response=$(curl -X POST \
                -H "Content-Type: application/json" \
                -H "api-key: ${{ secrets.DEVTO_API_KEY }}" \
                -d "$JSON_PAYLOAD" \
                https://dev.to/api/articles)
              
              echo "API Response: $response"
            fi
          done