name: Publish to Dev.to

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch [[1]]
    paths:
      - 'articles/**.md'  # Only trigger for Markdown files in the 'articles' folder

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Publish to Dev.to
        uses: sinedied/devto-cli@v1  # Use a specific release (e.g., v1) instead of the main branch [[6]]
        with:
          api-key: ${{ secrets.DEVTO_API_KEY }}
          files: 'articles/*.md'